In [5]:
#np.array 
import numpy as np 
a = np.array([1,2,3])
print(a ) 
print(type(a) )

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
#2d numpy and 3d numpy array - 1st we have to give two list for 2d array 
b = np.array([[1,2,3],[4,5,6] ])
print (b )
print (type(b ))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [11]:
c= np.array([ [ [1,2],[3,4]],[ [5,6],[7,8 ]] ])#this is 3d array from here i am typing and you restart again and again 
print (c) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
#dtype 
np.array([1,23,3], dtype = float )

array([ 1., 23.,  3.])

In [28]:
#np.arange
q=np.arange(13)
a=np.arange(1,10)
c= np.arange(10,2,-1)
d= np.arange(10,2,-2)
print(q)
print(a)
print(c)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[1 2 3 4 5 6 7 8 9]
[10  9  8  7  6  5  4  3]
[10  8  6  4]


In [38]:
#reshape 
np.arange(1,26).reshape(5,5,1)#here may be 3d array will be there 
np.arange(1,26).reshape(5,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [46]:
# np.ones and np.zeros
np.ones((3,2))
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [51]:
#np.random 
np.random.random((2,4))

array([[0.69266229, 0.88124832, 0.25958286, 0.16408678],
       [0.41090465, 0.28679283, 0.51741776, 0.54605201]])

In [53]:
#np.linspace -- it is leanear seprable it seprate the number in equal distance
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [54]:
#np.identity 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## array atribue 

In [64]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [58]:
#ndim  - it give you the dimension of the numpy array 
a3.ndim

3

In [59]:
#shape - it told us how many rows and column are there in the array 
print ( a2 . shape)


(3, 4)


In [60]:
print(a3.shape)

(2, 2, 2)


In [62]:
#size it told us how many items are there in the list
print (a3.size)


8


In [66]:
#item size - it told us what is the size of a array or item is in mb or bite or gb type bro dtype = np.int 32
a3.itemsize

4

In [68]:
#dtype.
print (a1.dtype)
print (a2.dtype)
print (a3.dtype)

int32
float64
int32


### changing datatype 

In [70]:
#astype  - it can change the type of previous made array means from int to float 
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

### array operation

In [79]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)

print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [80]:
#scalar opertation
# arithmatic operation +-*/ power all operation are done 

a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [84]:
#relational ><==!=
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [86]:
#vector operation performimg opertation on two []
#arithmatic 
a1*a2



array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# array function

In [89]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[92.,  5., 58.],
       [37., 67., 23.],
       [56., 58., 58.]])

In [90]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([190624.,  19430.,  77372.])

In [91]:
# mean/median/std/var
np.var(a1,axis=1)

array([1.28155556e+03, 3.36888889e+02, 8.88888889e-01])

In [92]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [94]:
#log and exponent   exp for exponent
np.log(a1)

array([[4.52178858, 1.60943791, 4.06044301],
       [3.61091791, 4.20469262, 3.13549422],
       [4.02535169, 4.06044301, 4.06044301]])

In [95]:
#round /ceil and floar
# round/floor/ceil

np.ceil(np.random.random((2,3))*100) # ceil aage waala number pa pekata hai aur floor uska peicha or nearest wala ka pass 

array([[ 59.,   7., 100.],
       [  2.,  45.,  27.]])

### indexing and slicing 


In [97]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [98]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
a1[-3]

7

In [99]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
a2[1,3]

7

In [106]:
a3[1,0,1]  #es 3d ka anndar kitnna 2d hai kuki 3d is made by using 2d array

5

In [107]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
a1[2:5:2]#here we are using slicing [2:4 ] here the last element is not included and last 2 is for alternate


array([2, 4])

In [116]:
a1[9:5:-2]

array([9, 7])