In [2]:
import numpy as np


In [3]:
#np.array
#it will can be  also called as vector
a = np.array([1,2,3])
print (a)
print(type(a))


[1 2 3]
<class 'numpy.ndarray'>


In [4]:
#2d and 3d array
#it can also called as materices 
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
 #dtype :- it is used to inside as a parameter for the type of array data 
np.array([1,2,3],dtype = float) 
np.array([1,2,3],dtype = bool) 
np.array([1,2,3],dtype = complex) 

array([1.+0.j, 2.+0.j, 3.+0.j])

In [6]:
# np.arrange  it give a range b\w number the 1st element is included and last one is excluded 
np.arange(1,11)
np.arange(1,11,2)


array([1, 3, 5, 7, 9])

In [76]:
#with reshape  it convert the shape of the array from diffrent (like from 1d to 2d or 3d)even 4d to like np.arange(16).reshape(2,2,2,2)
print (np.arange (1,11).reshape(5,2))
print()
print (np.arange (1,11).reshape(2,5))
print()
print (np.arange (1,31).reshape(6,5))
#ovisioly it will not work if you have less input for the matrix and vice-versa


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [78]:
#np.ones and  np.zeros 
#it create a numpy array whoes all value is ones and zeroes
print(np.ones((3,4))            ) 
print()
print(np.zeros((3,4)))
print()
print(np.random.random((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[3.61411458e-01 2.54167500e-01 5.98230388e-02 7.34268784e-01]
 [8.97527415e-02 9.06209978e-01 7.79120569e-01 8.75164018e-01]
 [5.95773342e-01 6.25187976e-04 5.11864229e-02 6.34301371e-01]]


In [9]:
#np.linspace it is used to create a linear seprable values in form of array means that it create equal distance pa point genrate karta hai means two number ka sub same he hoga 
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [10]:
#identity - it create a identity metrices of given parameter 
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Array Attribute

In [11]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)
a1

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#ndim- it give the dimension of the array like 2d or 3d
a3.ndim

3

In [13]:
#shape it give the shape of the array like its how many row and column are there in it
print(a3.shape)
#shape of a3 like there are two 2d array of shape 2,2
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
#size - it give us how many items are presnt in the given array
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [15]:
 #item size - it gives how much does the array occupy size in the memory
print(a1.itemsize)
print(a2.itemsize)#it is a float
print(a3.itemsize)


4
8
4


In [16]:
#dtype - anoter function of it is that it teels the type of the array
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# changing datatype

In [17]:
#astype 
a3.dtype

dtype('int32')

In [18]:
#astype- it change the datatype of it after intaialising
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

# Array Operations

In [19]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
 #scaler operations - we can do operation on array
#arithmatic: with every item wise
print(a1+2)
print(a1*2) 
print(a1%2)
print(a1-2)
print(a1**2)
print(a1/2)


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


In [21]:
#relational
print(a2>15) # it compare with every element of the array
print(a2==15)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False  True]
 [False False False False]
 [False False False False]]


In [22]:
#vector operation - it is done on two or more array(matrices)
# arithmatics
a1 ** a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

# Array Function

In [23]:
#random_number = np.random.random()
#print(random_number)
#Yes, the np.random.random function in NumPy generatesrandom floating-point numbers between 0 (inclusive) and 1 (exclusive). In other words, it produces random numbers in the half-open interval [0, 1), which means that the generated values can be equal to 0 but will never be equal to 1. Here's an example of how to use it:


In [24]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[65., 34., 33.],
       [84., 51., 57.],
       [29., 40., 12.]])

In [25]:
# max/min/sum/product
print(np.sum(a1))
print(np.max(a1))
print(np.min(a1))
print(np.product(a1))
print(np.prod(a1))

#if we want the min of every row than
# 0 -> column  1-> row
print(np.max(a1,axis=0))
print(np.max(a1,axis=1))

405.0
84.0
12.0
247896141292800.0
247896141292800.0
[84. 51. 57.]
[65. 84. 40.]


In [26]:
#mean/median/mode/std/var   we can use axis here too
print(np.mean(a1))
print(np.median(a1))
#  no mode function may be kuch aur hoga print(np.mode(a1))
print(np.std(a1))
print(np.var(a1))

print(np.mean(a1,axis=0))
print(np.mean(a1,axis=1))

45.0
40.0
20.374275719914834
415.1111111111111
[59.33333333 41.66666667 34.        ]
[44. 64. 27.]


In [27]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.82682868,  0.52908269,  0.99991186],
       [ 0.73319032,  0.67022918,  0.43616476],
       [-0.66363388,  0.74511316, -0.53657292]])

In [28]:
# dot product of matrices 
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [29]:
#log and exponents
print(np.exp(a1))
print(np.log(a1))

[[1.69488924e+28 5.83461743e+14 2.14643580e+14]
 [3.02507732e+36 1.40934908e+22 5.68572000e+24]
 [3.93133430e+12 2.35385267e+17 1.62754791e+05]]
[[4.17438727 3.52636052 3.49650756]
 [4.4308168  3.93182563 4.04305127]
 [3.36729583 3.68887945 2.48490665]]


In [30]:
#round/floor/ceil
print(np.random.random((2,3))*100)
print(np.round(np.random.random((2,3))*100))
print(np.floor(np.random.random((2,3))*100))
print(np.ceil(np.random.random((2,3))*100))
print()
print()
print("by apple")
print()
apple = np.random.random((2,3))*100
print(apple)
print()
print(np.round(apple))
print()
print(np.floor(apple))
print()
print(np.ceil(apple))


[[56.04503439  1.99760644 73.05772112]
 [91.01924294 54.55689935 52.9943829 ]]
[[40.  0. 76.]
 [56. 77. 84.]]
[[21. 69. 61.]
 [34. 31. 52.]]
[[75. 92. 84.]
 [66.  9. 77.]]


by apple

[[12.92407155  9.0841868  19.94883847]
 [25.96254774 56.43162504 70.8700085 ]]

[[13.  9. 20.]
 [26. 56. 71.]]

[[12.  9. 19.]
 [25. 56. 70.]]

[[13. 10. 20.]
 [26. 57. 71.]]


 ### Indexing and Slicing

In [31]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [32]:
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
print(a1[0])
print(a1[4])
print(a1[-2])
print(a1[-8])

0
4
8
2


In [34]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
print(a2[2,3])
print(a2[1,2])
print(a2[2,1])
print(a2[2,2])

11
6
9
10


In [36]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
print(a3[0,1,0])#first in which 2d array then its row and then column 
print(a3[0,0,0])

2
0


# slicing

In [38]:
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a1[2:5]#it is same as slicing in array
# 2 is included and 5 is excluded

array([2, 3, 4])

In [40]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
a2[0,:]#if i want the first row in the 2d array and also the (:) the colon is used to fetch all the element

array([0, 1, 2, 3])

In [42]:
#for coloumn for the 4th column 
a2[:,3]

array([ 3,  7, 11])

In [43]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [44]:
a2[::2,::3]#this colon colon include all element by jump of two in the row vice versa in column too

array([[ 0,  3],
       [ 8, 11]])

In [45]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [46]:
a2[1,::3]

array([4, 7])

In [47]:
a2[-3:-1,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [48]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [49]:
a3= np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [50]:
a3[1,0:,0:] # or a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [51]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [52]:
a3[0,1,:]

array([3, 4, 5])

In [53]:
 a3[0,1,]

array([3, 4, 5])

In [54]:
a3[1,:,1]

array([10, 13, 16])

In [55]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [56]:
 a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [57]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [59]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
for i in a2:
    print(i)
    #each row at a time

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [61]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [62]:
for i in np.nditer(a3):
    print(i,end = " ")
    #it converted into a 1d array then print;it

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

### Reshaping

In [63]:
#reshape

In [64]:
#transpose
np.transpose(a2)
#another it will give same result a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [65]:
#ravel:- it convert all dimension array into 1d
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Stacking

In [66]:
# horizontal stacking         ;; sape must be same
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [67]:
#horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [68]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [69]:
# horizontal spliting ---> equal division
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [71]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [72]:
 #vertical split 
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [73]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [74]:
np.vsplit(a5,2)

ValueError: array split does not result in an equal division