### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [205]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([87, 89, 71, 99, 56, 13, 42, 16, 41, 37,  1, 58, 60, 99, 59])

In [206]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[61, 42, 91, 66],
       [61, 16,  6, 31],
       [23,  3, 30, 83],
       [34, 89, 16, 74],
       [84, 22, 11, 47],
       [51, 62,  6, 31]])

In [207]:
np.sort(a)[::-1]

array([99, 99, 89, 87, 71, 60, 59, 58, 56, 42, 41, 37, 16, 13,  1])

In [208]:
np.sort(b,axis=0)

array([[23,  3,  6, 31],
       [34, 16,  6, 31],
       [51, 22, 11, 47],
       [61, 42, 16, 66],
       [61, 62, 30, 74],
       [84, 89, 91, 83]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [209]:
# code
np.append(a,200)

array([ 87,  89,  71,  99,  56,  13,  42,  16,  41,  37,   1,  58,  60,
        99,  59, 200])

In [210]:
b

array([[61, 42, 91, 66],
       [61, 16,  6, 31],
       [23,  3, 30, 83],
       [34, 89, 16, 74],
       [84, 22, 11, 47],
       [51, 62,  6, 31]])

In [211]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[6.10000000e+01, 4.20000000e+01, 9.10000000e+01, 6.60000000e+01,
        1.32365703e-01],
       [6.10000000e+01, 1.60000000e+01, 6.00000000e+00, 3.10000000e+01,
        5.21791386e-01],
       [2.30000000e+01, 3.00000000e+00, 3.00000000e+01, 8.30000000e+01,
        3.97292672e-01],
       [3.40000000e+01, 8.90000000e+01, 1.60000000e+01, 7.40000000e+01,
        3.09725730e-01],
       [8.40000000e+01, 2.20000000e+01, 1.10000000e+01, 4.70000000e+01,
        7.21534613e-02],
       [5.10000000e+01, 6.20000000e+01, 6.00000000e+00, 3.10000000e+01,
        4.26638724e-01]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [212]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [213]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [214]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [215]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [216]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [217]:
a


array([87, 89, 71, 99, 56, 13, 42, 16, 41, 37,  1, 58, 60, 99, 59])

In [218]:
np.expand_dims(a,axis=0)

array([[87, 89, 71, 99, 56, 13, 42, 16, 41, 37,  1, 58, 60, 99, 59]])

In [219]:
# code
a.shape

(15,)

In [220]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [221]:
np.expand_dims(a,axis=1)

array([[87],
       [89],
       [71],
       [99],
       [56],
       [13],
       [42],
       [16],
       [41],
       [37],
       [ 1],
       [58],
       [60],
       [99],
       [59]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [222]:
a

array([87, 89, 71, 99, 56, 13, 42, 16, 41, 37,  1, 58, 60, 99, 59])

In [223]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  2,  3,  4, 11, 12, 13, 14], dtype=int64),)

In [224]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0,  0,  0,  0,  0, 13, 42, 16, 41, 37,  1,  0,  0,  0,  0])

In [225]:
np.where(a%2 == 0,0,a)

array([87, 89, 71, 99,  0, 13,  0,  0, 41, 37,  1,  0,  0, 99, 59])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [226]:
# code
a

array([87, 89, 71, 99, 56, 13, 42, 16, 41, 37,  1, 58, 60, 99, 59])

In [227]:
np.argmax(a)

3

In [228]:
b

array([[61, 42, 91, 66],
       [61, 16,  6, 31],
       [23,  3, 30, 83],
       [34, 89, 16, 74],
       [84, 22, 11, 47],
       [51, 62,  6, 31]])

In [229]:
np.argmax(b,axis=0)

array([4, 3, 0, 2], dtype=int64)

In [230]:
np.argmax(b,axis=1)

array([2, 0, 3, 1, 0, 1], dtype=int64)

In [231]:
# np.argmin
np.argmin(a)

10

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [232]:
a

array([87, 89, 71, 99, 56, 13, 42, 16, 41, 37,  1, 58, 60, 99, 59])

In [233]:
np.cumsum(a)

array([ 87, 176, 247, 346, 402, 415, 457, 473, 514, 551, 552, 610, 670,
       769, 828])

In [234]:
b

array([[61, 42, 91, 66],
       [61, 16,  6, 31],
       [23,  3, 30, 83],
       [34, 89, 16, 74],
       [84, 22, 11, 47],
       [51, 62,  6, 31]])

In [235]:
np.cumsum(b,axis=1)

array([[ 61, 103, 194, 260],
       [ 61,  77,  83, 114],
       [ 23,  26,  56, 139],
       [ 34, 123, 139, 213],
       [ 84, 106, 117, 164],
       [ 51, 113, 119, 150]])

In [236]:
np.cumsum(b)

array([  61,  103,  194,  260,  321,  337,  343,  374,  397,  400,  430,
        513,  547,  636,  652,  726,  810,  832,  843,  890,  941, 1003,
       1009, 1040])

In [237]:
# np.cumprod
np.cumprod(a)

array([         87,        7743,      549753,    54425547, -1247136664,
         967092552,  1963181520,  1346133248,  -643111680,  1974671616,
        1974671616, -1433163264,   -90449920,  -364607488,   -37005312])

In [238]:
a

array([87, 89, 71, 99, 56, 13, 42, 16, 41, 37,  1, 58, 60, 99, 59])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [239]:
a

array([87, 89, 71, 99, 56, 13, 42, 16, 41, 37,  1, 58, 60, 99, 59])

In [240]:
np.percentile(a,100)#it means that it is the highest eska aaga koi nahi hai maimum

99.0

In [241]:
np.percentile(a,75)

79.0

In [242]:
np.percentile(a,0)

1.0

In [243]:
np.percentile(a,50)#percentil means kitna log current wala sa picha hai

58.0

In [244]:
np.median(a)

58.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [245]:
# code
a

array([87, 89, 71, 99, 56, 13, 42, 16, 41, 37,  1, 58, 60, 99, 59])

In [246]:
np.histogram(a,bins=[0,50,100])

(array([6, 9], dtype=int64), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [247]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [248]:
# code
a


array([87, 89, 71, 99, 56, 13, 42, 16, 41, 37,  1, 58, 60, 99, 59])

In [249]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([60])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [250]:
# code
a

array([87, 89, 71, 99, 56, 13, 42, 16, 41, 37,  1, 58, 60, 99, 59])

In [251]:
np.flip(a)

array([59, 99, 60, 58,  1, 37, 41, 16, 42, 13, 56, 99, 71, 89, 87])

In [252]:
b

array([[61, 42, 91, 66],
       [61, 16,  6, 31],
       [23,  3, 30, 83],
       [34, 89, 16, 74],
       [84, 22, 11, 47],
       [51, 62,  6, 31]])

In [253]:
np.flip(b,axis=1)

array([[66, 91, 42, 61],
       [31,  6, 16, 61],
       [83, 30,  3, 23],
       [74, 16, 89, 34],
       [47, 11, 22, 84],
       [31,  6, 62, 51]])

In [271]:
np.flip(b)

array([[31,  6, 62, 51],
       [47, 11, 22, 84],
       [74, 16, 89, 34],
       [83, 30,  3, 23],
       [31,  6, 16, 61],
       [66, 91, 42, 61]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [254]:
# code
a

array([87, 89, 71, 99, 56, 13, 42, 16, 41, 37,  1, 58, 60, 99, 59])

In [255]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [256]:
# code
a

array([110, 530,  71,  99,  56,  13,  42,  16,  41,  37,   1,  58,  60,
        99,  59])

In [257]:
np.delete(a,[0,2,4])

array([530,  99,  13,  42,  16,  41,  37,   1,  58,  60,  99,  59])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [258]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [259]:
np.intersect1d(m,n)

array([3, 4, 5])

In [260]:
np.setdiff1d(n,m)

array([6, 7])

In [272]:
np.setdiff1d(m,n)

array([1, 2])

In [261]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [262]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [263]:
# code
a

array([110, 530,  71,  99,  56,  13,  42,  16,  41,  37,   1,  58,  60,
        99,  59])

In [264]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 71, 75, 56, 25, 42, 25, 41, 37, 25, 58, 60, 75, 59])

In [265]:
# 17. np.swapaxes

In [266]:
# 18. np.uniform

In [267]:
# 19. np.count_nonzero

In [268]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [269]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [270]:

# 25. np.allclose and equals